### ISSUE TITLE
net_b mistake

### ISSUE THREAD

**Issue by xup5** [animikhaich/VGGNet-Tensorflow#2]
in VGGNet-Tensorflow/vgg_nets/net_b.py, should it be 
hidden = conv3_unit(64, inputs)
hidden = conv3_unit(64, **hidden**)

**Comment by xup5** [comment]
Also, other nets have the same issue.

**Comment by animikhaich** [comment]
@xup5 , Thanks for pointing out the mistake, it will be fixed in the next release.
